apiVersion: v1
kind: Service
metadata:
  name: lb1-project
  labels:
    app: lb1-project
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: lb1-project
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: lb1-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb1-project
  template:
    metadata:
      labels:
        app: lb1-project
        group: customer
        tier: frontend
    spec:
      containers:
      - name: lb1-project
        image: smokja/lb1-project        
        ports:
        - containerPort: 80
          name: lb1-project